# Generated by Django 2.1.1 on 2018-10-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveredCmm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.CharField(blank=True, max_length=5, null=True)),
                ('Jan', models.CharField(blank=True, max_length=5, null=True)),
                ('Feb', models.CharField(blank=True, max_length=5, null=True)),
                ('Mar', models.CharField(blank=True, max_length=5, null=True)),
                ('Apr', models.CharField(blank=True, max_length=5, null=True)),
                ('May', models.CharField(blank=True, max_length=5, null=True)),
                ('Jun', models.CharField(blank=True, max_length=5, null=True)),
                ('Jul', models.CharField(blank=True, max_length=5, null=True)),
                ('Aug', models.CharField(blank=True, max_length=5, null=True)),
                ('Sep', models.CharField(blank=True, max_length=5, null=True)),
                ('Oct', models.CharField(blank=True, max_length=5, null=True)),
                ('Nov', models.CharField(blank=True, max_length=5, null=True)),
                ('Dec', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'verbose_name': '生产发货量统计',
                'verbose_name_plural': '生产发货量统计',
            },
        ),
        migrations.CreateModel(
            name='InstalledCmm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.CharField(max_length=5)),
                ('Jan', models.CharField(blank=True, max_length=5, null=True)),
                ('Feb', models.CharField(blank=True, max_length=5, null=True)),
                ('Mar', models.CharField(blank=True, max_length=5, null=True)),
                ('Apr', models.CharField(blank=True, max_length=5, null=True)),
                ('May', models.CharField(blank=True, max_length=5, null=True)),
                ('Jun', models.CharField(blank=True, max_length=5, null=True)),
                ('Jul', models.CharField(blank=True, max_length=5, null=True)),
                ('Aug', models.CharField(blank=True, max_length=5, null=True)),
                ('Sep', models.CharField(blank=True, max_length=5, null=True)),
                ('Oct', models.CharField(blank=True, max_length=5, null=True)),
                ('Nov', models.CharField(blank=True, max_length=5, null=True)),
                ('Dec', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'verbose_name': '生产装机数量统计',
                'verbose_name_plural': '生产装机数量统计',
            },
        ),
        migrations.CreateModel(
            name='InstalledEachYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.CharField(blank=True, max_length=5, null=True)),
                ('Global_A', models.CharField(blank=True, max_length=5, null=True)),
                ('Global_B', models.CharField(blank=True, max_length=5, null=True)),
                ('Global_C', models.CharField(blank=True, max_length=5, null=True)),
                ('Global_D', models.CharField(blank=True, max_length=5, null=True)),
                ('Global_EF', models.CharField(blank=True, max_length=5, null=True)),
                ('Explorer', models.CharField(blank=True, max_length=5, null=True)),
                ('Inspector_Pioneer_InspectorP_GlobalP', models.CharField(blank=True, max_length=5, null=True)),
                ('MH3D_Inspector454_Explorer454', models.CharField(blank=True, max_length=5, null=True)),
                ('Optive_Vision', models.CharField(blank=True, max_length=5, null=True)),
                ('Toro_ToroImage', models.CharField(blank=True, max_length=5, null=True)),
                ('Micro_Plus', models.CharField(blank=True, max_length=5, null=True)),
                ('Alpha_Apollo', models.CharField(blank=True, max_length=5, null=True)),
                ('Function_Pluse', models.CharField(blank=True, max_length=5, null=True)),
                ('Zoo_ZC', models.CharField(blank=True, max_length=5, null=True)),
                ('Stinger_ll', models.CharField(blank=True, max_length=5, null=True)),
                ('Global_Mini', models.CharField(blank=True, max_length=5, null=True)),
                ('Auctual_Build_Qty', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'verbose_name': '历年生产装机量汇总',
                'verbose_name_plural': '历年生产装机量汇总',
            },
        ),
        migrations.CreateModel(
            name='NewOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.CharField(blank=True, max_length=5, null=True)),
                ('Jan', models.CharField(blank=True, max_length=5, null=True)),
                ('Feb', models.CharField(blank=True, max_length=5, null=True)),
                ('Mar', models.CharField(blank=True, max_length=5, null=True)),
                ('Apr', models.CharField(blank=True, max_length=5, null=True)),
                ('May', models.CharField(blank=True, max_length=5, null=True)),
                ('Jun', models.CharField(blank=True, max_length=5, null=True)),
                ('Jul', models.CharField(blank=True, max_length=5, null=True)),
                ('Aug', models.CharField(blank=True, max_length=5, null=True)),
                ('Sep', models.CharField(blank=True, max_length=5, null=True)),
                ('Oct', models.CharField(blank=True, max_length=5, null=True)),
                ('Nov', models.CharField(blank=True, max_length=5, null=True)),
                ('Dec', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'verbose_name': '新进生产订单数量汇总',
                'verbose_name_plural': '新进生产订单数量汇总',
            },
        ),
        migrations.CreateModel(
            name='WaitingOrderAndInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('YearAndMonth', models.CharField(blank=True, max_length=7, null=True)),
                ('OrderQty', models.CharField(blank=True, max_length=5, null=True)),
                ('ShipmentQty', models.CharField(blank=True, max_length=5, null=True)),
                ('AuctalAssemblyQty', models.CharField(blank=True, max_length=5, null=True)),
                ('ToBeExcutedTendency', models.CharField(blank=True, max_length=5, null=True)),
                ('BackLogTendency', models.CharField(blank=True, max_length=5, null=True)),
                ('NetAvailableTendency', models.CharField(blank=True, max_length=5, null=True)),
                ('Backlog', models.CharField(blank=True, max_length=5, null=True)),
                ('ToBeExcutedOrder', models.CharField(blank=True, max_length=5, null=True)),
                ('NetAvailable', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'verbose_name': '整机“待执行订单” & “证据库存” 数据汇总',
                'verbose_name_plural': '整机“待执行订单” & “整机库存” 数据汇总',
            },
        ),
    ]
