# Generated by Django 2.1.1 on 2018-10-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installedeachyear',
            name='Alpha_Apollo',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='installedeachyear',
            name='Auctual_Build_Qty',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='installedeachyear',
            name='Explorer',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='installedeachyear',
            name='Function_Pluse',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='installedeachyear',
            name='Global_A',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='installedeachyear',
            name='Global_B',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='installedeachyear',
            name='Global_C',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='installedeachyear',
            name='Global_D',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='installedeachyear',
            name='Global_EF',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='installedeachyear',
            name='Global_Mini',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='installedeachyear',
            name='Inspector_Pioneer_InspectorP_GlobalP',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='installedeachyear',
            name='MH3D_Inspector454_Explorer454',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='installedeachyear',
            name='Micro_Plus',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='installedeachyear',
            name='Optive_Vision',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='installedeachyear',
            name='Stinger_ll',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='installedeachyear',
            name='Toro_ToroImage',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='installedeachyear',
            name='Zoo_ZC',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
    ]
