# Generated by Django 2.1.1 on 2018-10-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op', '0002_auto_20181025_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installedcmm',
            name='Apr',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='installedcmm',
            name='Aug',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='installedcmm',
            name='Dec',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='installedcmm',
            name='Feb',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='installedcmm',
            name='Jan',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='installedcmm',
            name='Jul',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='installedcmm',
            name='Jun',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='installedcmm',
            name='Mar',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='installedcmm',
            name='May',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='installedcmm',
            name='Nov',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='installedcmm',
            name='Oct',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='installedcmm',
            name='Sep',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
    ]
