# Generated by Django 2.1.1 on 2019-01-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op', '0002_auto_20190107_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveredcmm',
            name='Apr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveredcmm',
            name='Aug',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveredcmm',
            name='Dec',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveredcmm',
            name='Jul',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveredcmm',
            name='Jun',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveredcmm',
            name='Mar',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveredcmm',
            name='May',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveredcmm',
            name='Nov',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveredcmm',
            name='Oct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveredcmm',
            name='Sep',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
