# Generated by Django 2.1.1 on 2018-10-31 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op', '0004_auto_20181029_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveredcmm',
            name='Apr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveredcmm',
            name='Aug',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveredcmm',
            name='Dec',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveredcmm',
            name='Feb',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveredcmm',
            name='Jan',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveredcmm',
            name='Jul',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveredcmm',
            name='Jun',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveredcmm',
            name='Mar',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveredcmm',
            name='May',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveredcmm',
            name='Nov',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveredcmm',
            name='Oct',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveredcmm',
            name='Sep',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='installedcmm',
            name='Apr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='installedcmm',
            name='Aug',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='installedcmm',
            name='Dec',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='installedcmm',
            name='Feb',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='installedcmm',
            name='Jan',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='installedcmm',
            name='Jul',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='installedcmm',
            name='Jun',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='installedcmm',
            name='Mar',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='installedcmm',
            name='May',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='installedcmm',
            name='Nov',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='installedcmm',
            name='Oct',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='installedcmm',
            name='Sep',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='installedeachyear',
            name='Alpha_Apollo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='installedeachyear',
            name='Auctual_Build_Qty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='installedeachyear',
            name='Explorer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='installedeachyear',
            name='Function_Pluse',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='installedeachyear',
            name='Global_A',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='installedeachyear',
            name='Global_B',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='installedeachyear',
            name='Global_C',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='installedeachyear',
            name='Global_D',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='installedeachyear',
            name='Global_EF',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='installedeachyear',
            name='Global_Mini',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='installedeachyear',
            name='Inspector_Pioneer_InspectorP_GlobalP',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='installedeachyear',
            name='MH3D_Inspector454_Explorer454',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='installedeachyear',
            name='Micro_Plus',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='installedeachyear',
            name='Optive_Vision',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='installedeachyear',
            name='Stinger_ll',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='installedeachyear',
            name='Toro_ToroImage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='installedeachyear',
            name='Year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='installedeachyear',
            name='Zoo_ZC',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='neworder',
            name='Apr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='neworder',
            name='Aug',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='neworder',
            name='Dec',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='neworder',
            name='Feb',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='neworder',
            name='Jan',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='neworder',
            name='Jul',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='neworder',
            name='Jun',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='neworder',
            name='Mar',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='neworder',
            name='May',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='neworder',
            name='Nov',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='neworder',
            name='Oct',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='neworder',
            name='Sep',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='neworder',
            name='Year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='waitingorderandinventory',
            name='AuctalAssemblyQty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waitingorderandinventory',
            name='BackLogTendency',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waitingorderandinventory',
            name='Backlog',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waitingorderandinventory',
            name='NetAvailable',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waitingorderandinventory',
            name='NetAvailableTendency',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waitingorderandinventory',
            name='OrderQty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waitingorderandinventory',
            name='ShipmentQty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waitingorderandinventory',
            name='ToBeExcutedOrder',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waitingorderandinventory',
            name='ToBeExcutedTendency',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
