# Generated by Django 2.1.1 on 2019-05-15 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Partlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smallparts.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(max_length=255, unique=True)),
                ('record_string', models.TextField()),
                ('machine_type', models.CharField(max_length=255)),
                ('part', models.CharField(max_length=255)),
                ('result', models.IntegerField(default=0)),
                ('order_no', models.IntegerField(null=True)),
                ('operator', models.CharField(max_length=255)),
                ('input_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SfmAjd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(max_length=255)),
                ('adj_date', models.DateField()),
                ('adj_reason', models.CharField(max_length=255)),
                ('adj_nbr', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SheetConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2000)),
                ('config_string', models.TextField()),
                ('version', models.IntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smallparts.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(max_length=255)),
                ('machine', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='sheet_config_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smallparts.SheetConfig'),
        ),
    ]
