# Generated by Django 2.1.1 on 2018-11-06 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Op',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op_id', models.IntegerField()),
                ('op_name', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name': '工步信息',
                'verbose_name_plural': '工步信息',
            },
        ),
        migrations.CreateModel(
            name='Prob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prob_info', models.CharField(max_length=20, verbose_name='测针信息')),
            ],
            options={
                'verbose_name': '测头信息',
                'verbose_name_plural': '测头信息',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sfg_id', models.IntegerField(default='123', verbose_name='SFG')),
                ('type_name', models.CharField(default='', max_length=20, verbose_name='机型')),
                ('prob', models.CharField(default='', max_length=20, verbose_name='测头')),
                ('qty', models.FloatField(default=1, max_length=4, verbose_name='数量')),
                ('standard_tiem', models.FloatField(max_length=4, verbose_name='标准工时')),
                ('real_time', models.FloatField(default='', max_length=4, verbose_name='实际工时')),
                ('date', models.DateField(auto_now=True)),
                ('op_id', models.ForeignKey(db_column='op_id', on_delete=django.db.models.deletion.CASCADE, to='report.Op', verbose_name='工步')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户名')),
            ],
            options={
                'verbose_name': '报工平台',
                'verbose_name_plural': '报工平台',
            },
        ),
        migrations.CreateModel(
            name='SfmProd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sfg_id', models.IntegerField(verbose_name='SFG')),
                ('type_name', models.CharField(max_length=30, verbose_name='机型')),
            ],
            options={
                'verbose_name': 'SFM信息',
                'verbose_name_plural': 'SFM信息',
            },
        ),
        migrations.CreateModel(
            name='SupportiveTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rest', models.FloatField(default=None, max_length=10, null=True, verbose_name='休息')),
                ('clean_time', models.FloatField(default=None, max_length=10, null=True, verbose_name='卫生')),
                ('inside_group', models.FloatField(default=None, max_length=10, null=True, verbose_name='组内')),
                ('outside_group', models.FloatField(default=None, max_length=10, null=True, verbose_name='组外')),
                ('complete_machine', models.FloatField(default=None, max_length=10, null=True, verbose_name='整机')),
                ('granite', models.FloatField(default=None, max_length=10, null=True, verbose_name='花岗石')),
                ('prob', models.FloatField(default=None, max_length=10, null=True, verbose_name='测头')),
                ('shortage', models.FloatField(default=None, max_length=10, null=True, verbose_name='补缺件')),
                ('plan_change', models.FloatField(default=None, max_length=10, null=True, verbose_name='计划调整')),
                ('human_quality_issue_rework', models.FloatField(default=None, max_length=10, null=True, verbose_name='人为质量问题返工')),
                ('item_quality_issue', models.FloatField(default=None, max_length=10, null=True, verbose_name='零件质量问题')),
                ('human_quality_issue_repair', models.FloatField(default=None, max_length=10, null=True, verbose_name='人为质量问题返修')),
                ('equipment_mantainence', models.FloatField(default=None, max_length=10, null=True, verbose_name='设备维护')),
                ('inventory_check', models.FloatField(default=None, max_length=10, null=True, verbose_name='库存核查')),
                ('quality_check', models.FloatField(default=None, max_length=10, null=True, verbose_name='质量审核')),
                ('document', models.FloatField(default=None, max_length=10, null=True, verbose_name='档案整理')),
                ('conference', models.FloatField(default=None, max_length=10, null=True, verbose_name='会议')),
                ('group_management', models.FloatField(default=None, max_length=10, null=True, verbose_name='班组管理')),
                ('record', models.FloatField(default=None, max_length=10, null=True, verbose_name='记录')),
                ('date', models.DateField(auto_now=True, verbose_name='日期')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '辅助工时',
                'verbose_name_plural': '辅助工时',
            },
        ),
        migrations.CreateModel(
            name='TypeStandard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=30, verbose_name='机型')),
                ('op_id', models.IntegerField(verbose_name='工步')),
                ('standard_time', models.CharField(max_length=10, verbose_name='标准工时')),
                ('prob_info', models.ForeignKey(blank=True, db_column='prob_info', null=True, on_delete=django.db.models.deletion.CASCADE, to='report.Prob', verbose_name='测头信息')),
            ],
            options={
                'verbose_name': '标准工时',
                'verbose_name_plural': '标准工时',
            },
        ),
    ]
