# Generated by Django 2.1.1 on 2018-10-31 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supportive_time', models.FloatField(max_length=4)),
                ('borrow_time', models.FloatField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sfg_id', models.IntegerField()),
                ('type_name', models.CharField(max_length=30)),
                ('op_id', models.IntegerField()),
                ('prob', models.CharField(max_length=20)),
                ('standard_tiem', models.FloatField(max_length=4)),
                ('real_time', models.FloatField(max_length=4)),
                ('date', models.DateField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TypeStandard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op_id', models.IntegerField()),
                ('op_name', models.CharField(max_length=10)),
                ('type_name', models.ForeignKey(db_column='type_name', on_delete=django.db.models.deletion.CASCADE, to='report.Report')),
            ],
        ),
        migrations.AddField(
            model_name='otherinfo',
            name='sfg_id',
            field=models.ForeignKey(db_column='sfg_id', on_delete=django.db.models.deletion.CASCADE, to='report.Report'),
        ),
    ]
