# Generated by Django 2.1.1 on 2018-11-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportivetime',
            name='clean_time',
            field=models.FloatField(blank=True, default=None, max_length=10, null=True, verbose_name='卫生'),
        ),
        migrations.AlterField(
            model_name='supportivetime',
            name='complete_machine',
            field=models.FloatField(blank=True, default=None, max_length=10, null=True, verbose_name='整机'),
        ),
        migrations.AlterField(
            model_name='supportivetime',
            name='conference',
            field=models.FloatField(blank=True, default=None, max_length=10, null=True, verbose_name='会议'),
        ),
        migrations.AlterField(
            model_name='supportivetime',
            name='document',
            field=models.FloatField(blank=True, default=None, max_length=10, null=True, verbose_name='档案整理'),
        ),
        migrations.AlterField(
            model_name='supportivetime',
            name='equipment_mantainence',
            field=models.FloatField(blank=True, default=None, max_length=10, null=True, verbose_name='设备维护'),
        ),
        migrations.AlterField(
            model_name='supportivetime',
            name='granite',
            field=models.FloatField(blank=True, default=None, max_length=10, null=True, verbose_name='花岗石'),
        ),
        migrations.AlterField(
            model_name='supportivetime',
            name='group_management',
            field=models.FloatField(blank=True, default=None, max_length=10, null=True, verbose_name='班组管理'),
        ),
        migrations.AlterField(
            model_name='supportivetime',
            name='human_quality_issue_repair',
            field=models.FloatField(blank=True, default=None, max_length=10, null=True, verbose_name='人为质量问题返修'),
        ),
        migrations.AlterField(
            model_name='supportivetime',
            name='human_quality_issue_rework',
            field=models.FloatField(blank=True, default=None, max_length=10, null=True, verbose_name='人为质量问题返工'),
        ),
        migrations.AlterField(
            model_name='supportivetime',
            name='inside_group',
            field=models.FloatField(blank=True, default=None, max_length=10, null=True, verbose_name='组内'),
        ),
        migrations.AlterField(
            model_name='supportivetime',
            name='inventory_check',
            field=models.FloatField(blank=True, default=None, max_length=10, null=True, verbose_name='库存核查'),
        ),
        migrations.AlterField(
            model_name='supportivetime',
            name='item_quality_issue',
            field=models.FloatField(blank=True, default=None, max_length=10, null=True, verbose_name='零件质量问题'),
        ),
        migrations.AlterField(
            model_name='supportivetime',
            name='outside_group',
            field=models.FloatField(blank=True, default=None, max_length=10, null=True, verbose_name='组外'),
        ),
        migrations.AlterField(
            model_name='supportivetime',
            name='plan_change',
            field=models.FloatField(blank=True, default=None, max_length=10, null=True, verbose_name='计划调整'),
        ),
        migrations.AlterField(
            model_name='supportivetime',
            name='prob',
            field=models.FloatField(blank=True, default=None, max_length=10, null=True, verbose_name='测头'),
        ),
        migrations.AlterField(
            model_name='supportivetime',
            name='quality_check',
            field=models.FloatField(blank=True, default=None, max_length=10, null=True, verbose_name='质量审核'),
        ),
        migrations.AlterField(
            model_name='supportivetime',
            name='record',
            field=models.FloatField(blank=True, default=None, max_length=10, null=True, verbose_name='记录'),
        ),
        migrations.AlterField(
            model_name='supportivetime',
            name='rest',
            field=models.FloatField(blank=True, default=None, max_length=10, null=True, verbose_name='休息'),
        ),
        migrations.AlterField(
            model_name='supportivetime',
            name='shortage',
            field=models.FloatField(blank=True, default=None, max_length=10, null=True, verbose_name='补缺件'),
        ),
    ]
