# Generated by Django 2.1.1 on 2018-11-01 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_sfmprod'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otherinfo',
            options={'verbose_name': '其他信息', 'verbose_name_plural': '其他信息'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': '报工平台', 'verbose_name_plural': '报工平台'},
        ),
        migrations.AlterModelOptions(
            name='sfmprod',
            options={'verbose_name': 'SFM信息', 'verbose_name_plural': 'SFM信息'},
        ),
        migrations.AlterModelOptions(
            name='typestandard',
            options={'verbose_name': '标准工时', 'verbose_name_plural': '标准工时'},
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='sfg_id',
            field=models.ForeignKey(db_column='sfg_id', on_delete=django.db.models.deletion.CASCADE, to='report.SfmProd'),
        ),
        migrations.AlterField(
            model_name='sfmprod',
            name='sfg_id',
            field=models.IntegerField(),
        ),
    ]
