# Generated by Django 2.1.1 on 2018-11-01 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20181101_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prob_info', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '测头信息',
                'verbose_name_plural': '测头信息',
            },
        ),
        migrations.AlterField(
            model_name='report',
            name='prob',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Prob'),
        ),
    ]
