# Generated by Django 2.1.1 on 2018-11-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_auto_20181101_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Op',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op_id', models.IntegerField()),
                ('op_name', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name': '测头信息',
                'verbose_name_plural': '测头信息',
            },
        ),
        migrations.AlterField(
            model_name='prob',
            name='prob_info',
            field=models.CharField(max_length=20),
        ),
    ]
