# Generated by Django 2.1.1 on 2018-11-01 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_auto_20181101_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='op_id',
            field=models.ForeignKey(db_column='op_id', on_delete=django.db.models.deletion.CASCADE, to='report.Op'),
        ),
    ]
