# Generated by Django 2.1.1 on 2018-11-07 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_coefficientsupport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='外借分类')),
            ],
        ),
    ]
