# Generated by Django 2.1.1 on 2018-11-01 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_auto_20181101_1431'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='op',
            options={'verbose_name': '工步信息', 'verbose_name_plural': '工步信息'},
        ),
    ]
