# Generated by Django 2.1.1 on 2018-11-08 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_borrow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrow',
            options={'verbose_name': '外借工时', 'verbose_name_plural': '外借'},
        ),
        migrations.AlterModelOptions(
            name='coefficientsupport',
            options={'verbose_name': '辅助工时系数', 'verbose_name_plural': '辅助工时系数'},
        ),
        migrations.AddField(
            model_name='coefficientsupport',
            name='borrow_time',
            field=models.FloatField(blank=True, default=0, max_length=10, null=True, verbose_name='外借'),
        ),
        migrations.AddField(
            model_name='supportivetime',
            name='borrow_name',
            field=models.CharField(default='', max_length=15, verbose_name='外借分类'),
        ),
        migrations.AddField(
            model_name='supportivetime',
            name='borrow_time',
            field=models.FloatField(blank=True, default=0, max_length=10, null=True, verbose_name='外借时间'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(default=datetime.date(2018, 11, 8)),
        ),
        migrations.AlterField(
            model_name='supportivetime',
            name='date',
            field=models.DateField(default=datetime.date(2018, 11, 8), verbose_name='日期'),
        ),
    ]
