# Generated by Django 2.1.1 on 2018-11-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_auto_20181101_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typestandard',
            name='standard_time',
            field=models.CharField(max_length=10, verbose_name='标准工时'),
        ),
    ]
