# Generated by Django 2.1.1 on 2018-11-08 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_auto_20181108_1421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': '制造工时', 'verbose_name_plural': '制造工时'},
        ),
    ]
