# Generated by Django 2.1.1 on 2018-11-09 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0010_auto_20181108_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(default=datetime.date(2018, 11, 9)),
        ),
        migrations.AlterField(
            model_name='report',
            name='type_name',
            field=models.CharField(default='', max_length=50, verbose_name='机型'),
        ),
        migrations.AlterField(
            model_name='sfmprod',
            name='type_name',
            field=models.CharField(max_length=50, verbose_name='机型'),
        ),
        migrations.AlterField(
            model_name='supportivetime',
            name='date',
            field=models.DateField(default=datetime.date(2018, 11, 9), verbose_name='日期'),
        ),
    ]
