# Generated by Django 2.1.1 on 2018-11-02 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0010_auto_20181101_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='typestandard',
            name='prob_info',
            field=models.ForeignKey(blank=True, db_column='prob_info', null=True, on_delete=django.db.models.deletion.CASCADE, to='report.Prob'),
        ),
        migrations.AlterField(
            model_name='typestandard',
            name='standard_time',
            field=models.CharField(max_length=10, verbose_name='TIME'),
        ),
    ]
