# Generated by Django 2.1.1 on 2018-11-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0011_auto_20181102_0853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='user_id',
        ),
        migrations.AddField(
            model_name='report',
            name='user',
            field=models.CharField(default='未填写', max_length=4),
        ),
    ]
