# Generated by Django 2.1.1 on 2018-11-09 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0011_auto_20181109_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupOp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=10, verbose_name='组名')),
                ('op_id', models.ForeignKey(db_column='op_id', on_delete=django.db.models.deletion.CASCADE, to='report.Op', verbose_name='工步')),
            ],
        ),
    ]
