# Generated by Django 2.1.1 on 2018-11-10 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0012_groupop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupop',
            options={'verbose_name': '工步与组对应关系', 'verbose_name_plural': '工步与组对应关系'},
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(default=datetime.date(2018, 11, 10)),
        ),
        migrations.AlterField(
            model_name='supportivetime',
            name='date',
            field=models.DateField(default=datetime.date(2018, 11, 10), verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='typestandard',
            name='standard_time',
            field=models.CharField(max_length=20, verbose_name='标准工时'),
        ),
        migrations.AlterField(
            model_name='typestandard',
            name='type_name',
            field=models.CharField(max_length=50, verbose_name='机型'),
        ),
    ]
