# Generated by Django 2.1.1 on 2018-11-20 13:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0013_auto_20181110_1807'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupop',
            options={'verbose_name': '班组长-工步与组对应关系', 'verbose_name_plural': '班组长-工步与组对应关系'},
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(default=datetime.date(2018, 11, 20)),
        ),
        migrations.AlterField(
            model_name='report',
            name='prob',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='测头'),
        ),
        migrations.AlterField(
            model_name='supportivetime',
            name='date',
            field=models.DateField(default=datetime.date(2018, 11, 20), verbose_name='日期'),
        ),
    ]
