# Generated by Django 2.1.1 on 2018-11-20 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0014_auto_20181120_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_full_name', to=settings.AUTH_USER_MODEL, verbose_name='用户名'),
        ),
    ]
