# Generated by Django 2.1.1 on 2018-11-22 12:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0016_supportivetime_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(default=datetime.date(2018, 11, 22)),
        ),
        migrations.AlterField(
            model_name='supportivetime',
            name='comments',
            field=models.CharField(blank=True, default=' ', max_length=250, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='supportivetime',
            name='date',
            field=models.DateField(default=datetime.date(2018, 11, 22), verbose_name='日期'),
        ),
    ]
