# Generated by Django 2.1.1 on 2018-11-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0017_auto_20181102_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='qty',
            field=models.FloatField(default=1, max_length=4),
        ),
    ]
