# Generated by Django 2.1.1 on 2018-11-25 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0018_auto_20181122_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_paid',
            field=models.IntegerField(default=0, max_length=1, verbose_name='是否申请加班费'),
        ),
        migrations.AddField(
            model_name='report',
            name='over_time',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='加班'),
        ),
        migrations.AddField(
            model_name='report',
            name='over_time_type',
            field=models.CharField(blank=True, default=0, max_length=3, null=True, verbose_name='加班种类'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(default=datetime.date(2018, 11, 25)),
        ),
        migrations.AlterField(
            model_name='supportivetime',
            name='borrow_name',
            field=models.CharField(blank=True, default=' ', max_length=15, null=True, verbose_name='外借分类'),
        ),
        migrations.AlterField(
            model_name='supportivetime',
            name='date',
            field=models.DateField(default=datetime.date(2018, 11, 25), verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='supportivetime',
            name='prob',
            field=models.FloatField(blank=True, default=0, max_length=10, null=True, verbose_name='物流搬运'),
        ),
    ]
