# Generated by Django 2.1.1 on 2018-11-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0019_auto_20181125_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='is_paid',
            field=models.CharField(default='N', max_length=1, verbose_name='是否申请加班费'),
        ),
    ]
