# Generated by Django 2.1.1 on 2018-11-26 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0020_auto_20181125_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPerform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=4, verbose_name='员工')),
                ('natural_time', models.FloatField(default=0, max_length=4, verbose_name='工作时间')),
                ('performance', models.CharField(default=0, max_length=4, verbose_name='个人绩效')),
                ('standard_time', models.CharField(default=0, max_length=4, verbose_name='标准工时')),
                ('real_time', models.FloatField(default=0, max_length=4, verbose_name='制造工时')),
                ('supportive_time', models.FloatField(default=0, max_length=4, verbose_name='辅助工时')),
                ('borrow_time', models.FloatField(default=0, max_length=4, verbose_name='外借工时')),
                ('kpi', models.FloatField(default=0, max_length=4, verbose_name='工效比')),
                ('efficiency', models.FloatField(default=0, max_length=4, verbose_name='工时有效率')),
                ('date', models.DateField()),
                ('username', models.FloatField(default=0, max_length=4, verbose_name='用户名')),
                ('group', models.CharField(default='None', max_length=8, verbose_name='组')),
            ],
            options={
                'verbose_name': '班组业绩统计',
                'verbose_name_plural': '班组业绩统计',
            },
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(default=datetime.date(2018, 11, 26)),
        ),
        migrations.AlterField(
            model_name='supportivetime',
            name='date',
            field=models.DateField(default=datetime.date(2018, 11, 26), verbose_name='日期'),
        ),
    ]
