# Generated by Django 2.1.1 on 2018-11-29 18:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0023_auto_20181127_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('over_time', models.FloatField(blank=True, default=0, null=True, verbose_name='加班')),
                ('over_time_type', models.CharField(blank=True, default=0, max_length=3, null=True, verbose_name='加班种类')),
                ('is_paid', models.CharField(default='N', max_length=1, verbose_name='是否申请加班费')),
                ('date', models.DateField(default=datetime.date(2018, 11, 29))),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户名')),
            ],
            options={
                'verbose_name': '加班信息',
                'verbose_name_plural': '加班信息',
            },
        ),
        migrations.AlterModelOptions(
            name='sfgcomments',
            options={'verbose_name': 'SFG备注信息', 'verbose_name_plural': 'SFG备注信息'},
        ),
        migrations.RemoveField(
            model_name='report',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='report',
            name='over_time',
        ),
        migrations.RemoveField(
            model_name='report',
            name='over_time_type',
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(default=datetime.date(2018, 11, 29)),
        ),
        migrations.AlterField(
            model_name='supportivetime',
            name='date',
            field=models.DateField(default=datetime.date(2018, 11, 29), verbose_name='日期'),
        ),
    ]
