# Generated by Django 2.1.1 on 2018-12-01 12:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0024_auto_20181129_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=4, null=True, verbose_name='用户')),
                ('action_log', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='动作')),
                ('detail_message', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='详情')),
                ('comments', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='备注')),
                ('date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户名')),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
            },
        ),
        migrations.AlterField(
            model_name='overtime',
            name='date',
            field=models.DateField(default=datetime.date(2018, 12, 1)),
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(default=datetime.date(2018, 12, 1)),
        ),
        migrations.AlterField(
            model_name='supportivetime',
            name='date',
            field=models.DateField(default=datetime.date(2018, 12, 1), verbose_name='日期'),
        ),
    ]
