# Generated by Django 2.1.1 on 2018-12-14 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0025_auto_20181201_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtime',
            name='date',
            field=models.DateField(default=datetime.date(2018, 12, 14)),
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(default=datetime.date(2018, 12, 14)),
        ),
        migrations.AlterField(
            model_name='supportivetime',
            name='borrow_time',
            field=models.FloatField(default=0, max_length=10, verbose_name='外借时间'),
        ),
        migrations.AlterField(
            model_name='supportivetime',
            name='clean_time',
            field=models.FloatField(default=0, max_length=10, verbose_name='卫生'),
        ),
        migrations.AlterField(
            model_name='supportivetime',
            name='complete_machine',
            field=models.FloatField(default=0, max_length=10, verbose_name='整机'),
        ),
        migrations.AlterField(
            model_name='supportivetime',
            name='conference',
            field=models.FloatField(default=0, max_length=10, verbose_name='会议'),
        ),
        migrations.AlterField(
            model_name='supportivetime',
            name='date',
            field=models.DateField(default=datetime.date(2018, 12, 14), verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='supportivetime',
            name='document',
            field=models.FloatField(default=0, max_length=10, verbose_name='档案整理'),
        ),
        migrations.AlterField(
            model_name='supportivetime',
            name='equipment_mantainence',
            field=models.FloatField(default=0, max_length=10, verbose_name='设备维护'),
        ),
        migrations.AlterField(
            model_name='supportivetime',
            name='granite',
            field=models.FloatField(default=0, max_length=10, verbose_name='花岗石'),
        ),
        migrations.AlterField(
            model_name='supportivetime',
            name='group_management',
            field=models.FloatField(default=0, max_length=10, verbose_name='班组管理'),
        ),
        migrations.AlterField(
            model_name='supportivetime',
            name='human_quality_issue_repair',
            field=models.FloatField(default=0, max_length=10, verbose_name='人为质量问题返修'),
        ),
        migrations.AlterField(
            model_name='supportivetime',
            name='human_quality_issue_rework',
            field=models.FloatField(default=0, max_length=10, verbose_name='人为质量问题返工'),
        ),
        migrations.AlterField(
            model_name='supportivetime',
            name='inside_group',
            field=models.FloatField(default=0, max_length=10, verbose_name='组内'),
        ),
        migrations.AlterField(
            model_name='supportivetime',
            name='inventory_check',
            field=models.FloatField(default=0, max_length=10, verbose_name='库存核查'),
        ),
        migrations.AlterField(
            model_name='supportivetime',
            name='item_quality_issue',
            field=models.FloatField(default=0, max_length=10, verbose_name='零件质量问题'),
        ),
        migrations.AlterField(
            model_name='supportivetime',
            name='outside_group',
            field=models.FloatField(default=0, max_length=10, verbose_name='组外'),
        ),
        migrations.AlterField(
            model_name='supportivetime',
            name='plan_change',
            field=models.FloatField(default=0, max_length=10, verbose_name='计划调整'),
        ),
        migrations.AlterField(
            model_name='supportivetime',
            name='prob',
            field=models.FloatField(default=0, max_length=10, verbose_name='物流搬运'),
        ),
        migrations.AlterField(
            model_name='supportivetime',
            name='quality_check',
            field=models.FloatField(default=0, max_length=10, verbose_name='质量审核'),
        ),
        migrations.AlterField(
            model_name='supportivetime',
            name='record',
            field=models.FloatField(default=0, max_length=10, verbose_name='记录'),
        ),
        migrations.AlterField(
            model_name='supportivetime',
            name='rest',
            field=models.FloatField(default=0, max_length=10, verbose_name='休息'),
        ),
        migrations.AlterField(
            model_name='supportivetime',
            name='shortage',
            field=models.FloatField(default=0, max_length=10, verbose_name='补缺件'),
        ),
    ]
