# Generated by Django 2.1.1 on 2018-12-19 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0027_auto_20181217_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualLeave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=4, verbose_name='用户')),
                ('leave_type', models.CharField(max_length=3, verbose_name='用户')),
                ('start_date', models.DateTimeField(verbose_name='开始日期')),
                ('end_date', models.DateTimeField(verbose_name='截止日期')),
                ('hours', models.FloatField(default=0, verbose_name='时间')),
                ('remarks', models.CharField(max_length=30, verbose_name='用户')),
            ],
            options={
                'verbose_name': '休假',
                'verbose_name_plural': '休假',
            },
        ),
        migrations.AlterField(
            model_name='overtime',
            name='date',
            field=models.DateField(default=datetime.date(2018, 12, 19)),
        ),
        migrations.AlterField(
            model_name='overtime',
            name='is_paid',
            field=models.CharField(default=0, max_length=1, verbose_name='是否申请加班费'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(default=datetime.date(2018, 12, 19)),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_time',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2018, 12, 19, 9, 2, 53, 313925), verbose_name='提交时间'),
        ),
        migrations.AlterField(
            model_name='supportivetime',
            name='date',
            field=models.DateField(default=datetime.date(2018, 12, 19), verbose_name='日期'),
        ),
    ]
