# Generated by Django 2.1.1 on 2018-12-19 18:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0028_auto_20181219_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualleave',
            name='remarks',
            field=models.CharField(max_length=30, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_time',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2018, 12, 19, 18, 9, 31, 681769), verbose_name='提交时间'),
        ),
        migrations.AlterField(
            model_name='tracelog',
            name='detail_message',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='详情'),
        ),
    ]
