# Generated by Django 2.1.1 on 2018-12-20 11:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0029_auto_20181219_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtime',
            name='date',
            field=models.DateField(default=datetime.date(2018, 12, 20)),
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(default=datetime.date(2018, 12, 20)),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_time',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2018, 12, 20, 11, 3, 3, 808421), verbose_name='提交时间'),
        ),
        migrations.AlterField(
            model_name='supportivetime',
            name='date',
            field=models.DateField(default=datetime.date(2018, 12, 20), verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='tracelog',
            name='comments',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='备注'),
        ),
    ]
