# Generated by Django 2.1.1 on 2018-12-20 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0030_auto_20181220_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date_time',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2018, 12, 20, 11, 9, 13, 638271), verbose_name='提交时间'),
        ),
        migrations.AlterField(
            model_name='tracelog',
            name='comments',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='tracelog',
            name='detail_message',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='详情'),
        ),
    ]
