# Generated by Django 2.1.1 on 2018-12-28 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0031_auto_20181220_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtime',
            name='groups',
            field=models.CharField(default='', max_length=20, verbose_name='班组'),
        ),
        migrations.AddField(
            model_name='report',
            name='groups',
            field=models.CharField(default='', max_length=20, verbose_name='班组'),
        ),
        migrations.AddField(
            model_name='supportivetime',
            name='groups',
            field=models.CharField(default='', max_length=20, verbose_name='班组'),
        ),
        migrations.AlterField(
            model_name='overtime',
            name='date',
            field=models.DateField(default=datetime.date(2018, 12, 28)),
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(default=datetime.date(2018, 12, 28)),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_time',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2018, 12, 28, 18, 26, 20, 227713), verbose_name='提交时间'),
        ),
        migrations.AlterField(
            model_name='supportivetime',
            name='date',
            field=models.DateField(default=datetime.date(2018, 12, 28), verbose_name='日期'),
        ),
    ]
