# Generated by Django 2.1.1 on 2019-01-02 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0033_auto_20181229_1047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usergroups',
            options={'verbose_name': '用户工作组', 'verbose_name_plural': '用户工作组'},
        ),
        migrations.AlterModelOptions(
            name='workgroups',
            options={'verbose_name': '所有组', 'verbose_name_plural': '所有组'},
        ),
        migrations.AddField(
            model_name='groupperform',
            name='work_group',
            field=models.CharField(default='', max_length=10, verbose_name='工作组'),
        ),
        migrations.AlterField(
            model_name='groupperform',
            name='group',
            field=models.CharField(default='None', max_length=10, verbose_name='原班组'),
        ),
        migrations.AlterField(
            model_name='overtime',
            name='date',
            field=models.DateField(default=datetime.date(2019, 1, 2)),
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(default=datetime.date(2019, 1, 2)),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_time',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2019, 1, 2, 16, 52, 8, 116738), verbose_name='提交时间'),
        ),
        migrations.AlterField(
            model_name='report',
            name='groups',
            field=models.CharField(default='', max_length=20, verbose_name='工作组组'),
        ),
        migrations.AlterField(
            model_name='supportivetime',
            name='date',
            field=models.DateField(default=datetime.date(2019, 1, 2), verbose_name='日期'),
        ),
    ]
