# Generated by Django 2.1.1 on 2019-01-04 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0034_auto_20190102_1652'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='coefficientsupport',
            name='prob',
            field=models.FloatField(blank=True, default=0, max_length=10, null=True, verbose_name='物流搬运'),
        ),
        migrations.AlterField(
            model_name='overtime',
            name='date',
            field=models.DateField(default=datetime.date(2019, 1, 4)),
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(default=datetime.date(2019, 1, 4)),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_time',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2019, 1, 4, 10, 46, 23, 575387), verbose_name='提交时间'),
        ),
        migrations.AlterField(
            model_name='supportivetime',
            name='date',
            field=models.DateField(default=datetime.date(2019, 1, 4), verbose_name='日期'),
        ),
    ]
