# Generated by Django 2.1.1 on 2019-01-07 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0036_auto_20190107_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date_time',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2019, 1, 7, 15, 34, 44, 108730), verbose_name='提交时间'),
        ),
    ]
