# Generated by Django 2.1.1 on 2019-01-08 08:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0038_auto_20190107_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sfg', models.CharField(max_length=20, verbose_name='SFG')),
                ('info', models.CharField(max_length=50, verbose_name='信息')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '归档信息',
                'verbose_name_plural': '归档信息',
            },
        ),
        migrations.CreateModel(
            name='DocType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, verbose_name='归档种类')),
            ],
            options={
                'verbose_name': '归档种类',
                'verbose_name_plural': '归档种类',
            },
        ),
        migrations.AlterField(
            model_name='overtime',
            name='date',
            field=models.DateField(default=datetime.date(2019, 1, 8)),
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(default=datetime.date(2019, 1, 8)),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_time',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2019, 1, 8, 8, 32, 52, 530863), verbose_name='提交时间'),
        ),
        migrations.AlterField(
            model_name='supportivetime',
            name='date',
            field=models.DateField(default=datetime.date(2019, 1, 8), verbose_name='日期'),
        ),
        migrations.AddField(
            model_name='docinfo',
            name='type',
            field=models.ForeignKey(db_column='type', default='', on_delete=django.db.models.deletion.CASCADE, to='report.DocType', verbose_name='归档种类'),
        ),
    ]
