# Generated by Django 2.1.1 on 2019-01-08 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0039_auto_20190108_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctype',
            name='type_id',
            field=models.CharField(default='', max_length=20, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_time',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2019, 1, 8, 10, 5, 16, 715219), verbose_name='提交时间'),
        ),
    ]
