# Generated by Django 2.1.1 on 2019-01-08 19:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0040_auto_20190108_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docinfo',
            name='info',
            field=models.CharField(default=0, max_length=50, verbose_name='信息'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_time',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2019, 1, 8, 19, 12, 49, 308), verbose_name='提交时间'),
        ),
    ]
