# Generated by Django 2.1.1 on 2019-01-09 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0041_auto_20190108_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctype',
            name='type',
            field=models.CharField(max_length=20, unique=True, verbose_name='归档种类'),
        ),
        migrations.AlterField(
            model_name='doctype',
            name='type_id',
            field=models.CharField(default='', max_length=20, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='overtime',
            name='date',
            field=models.DateField(default=datetime.date(2019, 1, 9)),
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(default=datetime.date(2019, 1, 9)),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_time',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2019, 1, 9, 14, 38, 55, 391241), verbose_name='提交时间'),
        ),
        migrations.AlterField(
            model_name='supportivetime',
            name='date',
            field=models.DateField(default=datetime.date(2019, 1, 9), verbose_name='日期'),
        ),
    ]
