# Generated by Django 2.1.1 on 2019-02-28 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0043_auto_20190226_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtime',
            name='date',
            field=models.DateField(default=datetime.date(2019, 2, 28)),
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(default=datetime.date(2019, 2, 28)),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_time',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2019, 2, 28, 16, 47, 27, 397562), verbose_name='提交时间'),
        ),
        migrations.AlterField(
            model_name='sfgcomments',
            name='comments',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='sfgcomments',
            name='sfg',
            field=models.CharField(max_length=20, verbose_name='SFG'),
        ),
        migrations.AlterField(
            model_name='supportivetime',
            name='date',
            field=models.DateField(default=datetime.date(2019, 2, 28), verbose_name='日期'),
        ),
    ]
