# Generated by Django 2.1.1 on 2019-03-11 11:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0044_auto_20190228_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.CharField(max_length=20, verbose_name='编号')),
                ('name', models.CharField(max_length=20, verbose_name='物料名称')),
                ('unit', models.CharField(max_length=10, verbose_name='单位')),
                ('attribute', models.CharField(max_length=20, verbose_name='属性')),
                ('comments', models.CharField(max_length=20, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialApprove',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(max_length=4, verbose_name='年份')),
                ('quarter', models.CharField(max_length=10, verbose_name='季度')),
                ('qty', models.IntegerField(verbose_name='数量')),
                ('date', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='report.WorkGroups', verbose_name='班组')),
                ('sno', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='report.Material', verbose_name='物料编号')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户名')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialGet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(max_length=4, verbose_name='年份')),
                ('quarter', models.CharField(max_length=10, verbose_name='季度')),
                ('qty', models.IntegerField(verbose_name='数量')),
                ('date', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='report.WorkGroups', verbose_name='班组')),
                ('sno', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='report.Material', verbose_name='物料编号')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户名')),
            ],
        ),
        migrations.CreateModel(
            name='MeterialSurplus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(max_length=4, verbose_name='年份')),
                ('quarter', models.CharField(max_length=10, verbose_name='季度')),
                ('qty', models.IntegerField(verbose_name='数量')),
                ('date', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='report.WorkGroups', verbose_name='班组')),
                ('sno', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='report.Material', verbose_name='物料编号')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户名')),
            ],
        ),
        migrations.CreateModel(
            name='MeterialUse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(max_length=4, verbose_name='年份')),
                ('quarter', models.CharField(max_length=10, verbose_name='季度')),
                ('qty', models.IntegerField(verbose_name='数量')),
                ('date', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='report.WorkGroups', verbose_name='班组')),
                ('sno', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='report.Material', verbose_name='物料编号')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户名')),
            ],
        ),
        migrations.AlterField(
            model_name='overtime',
            name='date',
            field=models.DateField(default=datetime.date(2019, 3, 11)),
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(default=datetime.date(2019, 3, 11)),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_time',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2019, 3, 11, 11, 10, 18, 926810), verbose_name='提交时间'),
        ),
        migrations.AlterField(
            model_name='supportivetime',
            name='date',
            field=models.DateField(default=datetime.date(2019, 3, 11), verbose_name='日期'),
        ),
    ]
