# Generated by Django 2.1.1 on 2019-03-26 10:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0045_auto_20190315_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialget',
            name='qty',
            field=models.IntegerField(default=0, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='meterialsurplus',
            name='qty',
            field=models.FloatField(default=0, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='meterialuse',
            name='qty',
            field=models.FloatField(default=0, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_time',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2019, 3, 26, 10, 43, 55, 10270), verbose_name='提交时间'),
        ),
        migrations.AddField(
            model_name='materialapprove',
            name='qty_get',
            field=models.IntegerField(default=0, verbose_name='到货'),
        ),
        migrations.AddField(
            model_name='materialapprove',
            name='qty_sup',
            field=models.FloatField(default=0, verbose_name='结余数量'),
        ),
    ]
