# Generated by Django 2.1.1 on 2019-03-29 16:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0047_auto_20190326_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_no', models.CharField(default='', max_length=10, verbose_name='工号')),
                ('duty', models.CharField(default='', max_length=10, verbose_name='职位')),
                ('email', models.CharField(default='', max_length=50, verbose_name='邮箱')),
                ('department', models.CharField(default='', max_length=30, verbose_name='部门')),
                ('mobile', models.IntegerField(verbose_name='电话')),
                ('user_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户名')),
                ('work_group', models.ForeignKey(db_column='group_name', default='', on_delete=django.db.models.deletion.CASCADE, to='report.WorkGroups', verbose_name='工作组')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
    ]
