# Generated by Django 2.1.1 on 2019-04-03 09:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0048_auto_20190329_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportivetime',
            name='date_create',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2019, 4, 3, 9, 33, 5, 325154), verbose_name='创建时间'),
        ),
    ]
