# Generated by Django 2.1.1 on 2019-08-22 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0049_auto_20190403_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='cost_rate',
            field=models.FloatField(default=0, max_length=4, verbose_name='费率'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='quote',
            field=models.FloatField(default=0, max_length=4, verbose_name='报价'),
        ),
    ]
