# Generated by Django 2.1.1 on 2019-10-07 12:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0050_auto_20190822_1604'),
    ]

    operations = [
       
    ]
