# Generated by Django 2.1.1 on 2019-11-26 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0050_auto_20190822_1604'),
    ]

    operations = [

       
    ]
