# Generated by Django 2.1.1 on 2019-09-24 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0050_auto_20190822_1604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': '物耗材料', 'verbose_name_plural': '物耗材料'},
        ),
        migrations.AlterModelOptions(
            name='materialapprove',
            options={'verbose_name': '物耗申请审批', 'verbose_name_plural': '物耗申请审批'},
        ),
        migrations.AlterModelOptions(
            name='materialget',
            options={'verbose_name': '物耗材料到货', 'verbose_name_plural': '物耗材料到货'},
        ),
        migrations.AlterModelOptions(
            name='meterialsurplus',
            options={'verbose_name': '物耗结余', 'verbose_name_plural': '物耗结余'},
        ),
        migrations.AlterModelOptions(
            name='meterialuse',
            options={'verbose_name': '物耗领用', 'verbose_name_plural': '物耗领用'},
        ),
        migrations.AlterField(
            model_name='materialapprove',
            name='qty',
            field=models.IntegerField(default=0, verbose_name='审批数量'),
        ),
        migrations.AlterField(
            model_name='materialapprove',
            name='qty_request',
            field=models.IntegerField(default=0, verbose_name='申请数量'),
        ),
        migrations.AlterField(
            model_name='meterialuse',
            name='year',
            field=models.IntegerField(verbose_name='年份'),
        ),
        migrations.AlterField(
            model_name='overtime',
            name='date',
            field=models.DateField(default=datetime.date(2019, 9, 24)),
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_time',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2019, 9, 24, 11, 28, 51, 546582), verbose_name='提交时间'),
        ),
        migrations.AlterField(
            model_name='supportivetime',
            name='date',
            field=models.DateField(verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='supportivetime',
            name='date_create',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2019, 9, 24, 11, 28, 51, 546582), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='supportivetime',
            name='groups',
            field=models.CharField(default='', max_length=20, verbose_name='工作班组'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='mobile',
            field=models.IntegerField(blank=True, verbose_name='电话'),
        ),
    ]
