# Generated by Django 2.1.1 on 2019-11-28 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0051_auto_20191007_1230'),
    ]

    operations = [

        migrations.AddField(
            model_name='op',
            name='value_para',
            field=models.FloatField(default=1, max_length=4, verbose_name='系数'),
        ),
        migrations.AddField(
            model_name='sfmprod',
            name='attribute',
            field=models.CharField(default='非小部件', max_length=50, verbose_name='属性'),
        ),
       

    ]
