# Generated by Django 2.1.1 on 2019-10-23 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0052_auto_20190924_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtime',
            name='date',
            field=models.DateField(default=datetime.date(2019, 10, 23)),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_time',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2019, 10, 23, 13, 47, 26, 333571), verbose_name='提交时间'),
        ),
        migrations.AlterField(
            model_name='supportivetime',
            name='date_create',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2019, 10, 23, 13, 47, 26, 349171), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='tracelog',
            name='action_log',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='动作'),
        ),
        migrations.AlterField(
            model_name='tracelog',
            name='username',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='用户'),
        ),
    ]
