# Generated by Django 2.1.1 on 2020-01-07 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0053_auto_20200106_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(verbose_name='年份')),
                ('qty', models.FloatField(default=0, verbose_name='数量')),
                ('comments', models.CharField(default='', max_length=100, verbose_name='备注')),
            ],
            options={
                'verbose_name': '工作日统计',
                'verbose_name_plural': '工作日统计',
            },
        ),
        
    ]
