# Generated by Django 2.1.1 on 2020-01-14 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0054_auto_20200107_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='workdays',
            name='year',
            field=models.IntegerField(default=2019, verbose_name='年'),
        ),
        migrations.AlterField(
            model_name='annualleave',
            name='remarks',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='overtime',
            name='date',
            field=models.DateField(default=datetime.date(2020, 1, 14)),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_time',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2020, 1, 14, 10, 46, 49, 289452), verbose_name='提交时间'),
        ),
        migrations.AlterField(
            model_name='supportivetime',
            name='date_create',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2020, 1, 14, 10, 46, 49, 289452), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='tracelog',
            name='comments',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='tracelog',
            name='detail_message',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='详情'),
        ),
        migrations.AlterField(
            model_name='workdays',
            name='comments',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='workdays',
            name='month',
            field=models.IntegerField(verbose_name='月份'),
        ),
    ]
