# Generated by Django 2.1.1 on 2018-10-24 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveredTotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.CharField(max_length=5)),
                ('Jan', models.CharField(blank=True, max_length=5, null=True)),
                ('Feb', models.CharField(blank=True, max_length=5, null=True)),
                ('Mar', models.CharField(blank=True, max_length=5, null=True)),
                ('Apr', models.CharField(blank=True, max_length=5, null=True)),
                ('May', models.CharField(blank=True, max_length=5, null=True)),
                ('Jun', models.CharField(blank=True, max_length=5, null=True)),
                ('Jul', models.CharField(blank=True, max_length=5, null=True)),
                ('Aug', models.CharField(blank=True, max_length=5, null=True)),
                ('Sep', models.CharField(blank=True, max_length=5, null=True)),
                ('Oct', models.CharField(blank=True, max_length=5, null=True)),
                ('Nov', models.CharField(blank=True, max_length=5, null=True)),
                ('Dec', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'verbose_name': '发货缺件',
                'verbose_name_plural': '发货缺件',
            },
        ),
        migrations.CreateModel(
            name='Overdue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=10, null=True)),
                ('quantity', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'verbose_name': '超期分类',
                'verbose_name_plural': '超期分类',
            },
        ),
        migrations.CreateModel(
            name='ReasonAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_category', models.CharField(blank=True, max_length=15, null=True)),
                ('quantity', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': '原因分析',
                'verbose_name_plural': '原因分析',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'verbose_name': '供应商',
                'verbose_name_plural': '供应商',
            },
        ),
    ]
