# Generated by Django 2.1.1 on 2018-10-31 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortageConf', '0002_auto_20181029_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveredtotal',
            name='Apr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveredtotal',
            name='Aug',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveredtotal',
            name='Dec',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveredtotal',
            name='Feb',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveredtotal',
            name='Jan',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveredtotal',
            name='Jul',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveredtotal',
            name='Jun',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveredtotal',
            name='Mar',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveredtotal',
            name='May',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveredtotal',
            name='Nov',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveredtotal',
            name='Oct',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveredtotal',
            name='Sep',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='overdue',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reasonanalysis',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
