# Generated by Django 2.1.1 on 2019-10-07 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0051_auto_20191007_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_fix_date', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='最后修改时间')),
                ('create_date', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='创建时间')),
                ('contract', models.CharField(default='', max_length=30, verbose_name='合同号')),
                ('a_type', models.CharField(blank=True, default='', max_length=100, verbose_name='类别')),
                ('a_category', models.CharField(blank=True, default='', max_length=100, verbose_name='大类')),
                ('a_subject', models.CharField(blank=True, default='', max_length=100, verbose_name='科目')),
                ('real_time', models.FloatField(default=0, max_length=4, verbose_name='实际工时')),
                ('quote', models.FloatField(default=0, max_length=4, verbose_name='报价')),
                ('cost_rate', models.FloatField(default=0, max_length=4, verbose_name='费率')),
                ('standard', models.FloatField(default=0, max_length=4, verbose_name='标准价值工时')),
                ('confirmed', models.FloatField(default=0, max_length=4, verbose_name='确认价值工时')),
                ('attach', models.CharField(blank=True, default='', max_length=200, verbose_name='附件')),
                ('b_category', models.CharField(blank=True, default='', max_length=100, verbose_name='外借科目大类')),
                ('b_subject', models.CharField(blank=True, default='', max_length=100, verbose_name='外借科目小类')),
                ('expense', models.FloatField(blank=True, default=0, max_length=10, verbose_name='期间费用')),
                ('original_group', models.CharField(default='', max_length=20, verbose_name='原班组')),
                ('work_group', models.CharField(default='', max_length=20, verbose_name='工作组')),
                ('comments', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('date', models.DateField()),
                ('last_fix_user', models.CharField(default='', max_length=5, verbose_name='最后修改人')),
                ('last_fix_status', models.CharField(default='', max_length=1000, verbose_name='最后修改状态')),
                ('is_active', models.BooleanField(default=False)),
                ('flexible', models.TextField(blank=True, default='', null=True, verbose_name='浮动列')),
                ('username', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户名')),
            ],
            options={
                'verbose_name': '非制造工时统计',
                'verbose_name_plural': '非制造工时统计',
            },
        ),
        migrations.CreateModel(
            name='AssisType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_fix_date', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='最后修改时间')),
                ('create_date', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='创建时间')),
                ('a_type', models.CharField(default='', max_length=100, verbose_name='类别')),
                ('a_category', models.CharField(blank=True, default='', max_length=100, verbose_name='大类')),
                ('a_subject', models.CharField(default='', max_length=100, verbose_name='小类')),
                ('b_category', models.CharField(blank=True, default='', max_length=100, verbose_name='外借科目大类')),
                ('b_subject', models.CharField(blank=True, default='', max_length=100, verbose_name='外借科目小类')),
                ('b_old_category', models.CharField(default='', max_length=100, verbose_name='对应老辅助工时或者外借工时')),
                ('last_fix_user', models.CharField(default='', max_length=5, verbose_name='最后修改人')),
                ('last_fix_status', models.CharField(default='', max_length=200, verbose_name='最后修改状态')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否生效')),
                ('flexible', models.TextField(blank=True, default='', null=True, verbose_name='保留列')),
                ('create_user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '非制造工时种类',
                'verbose_name_plural': '非制造工时种类',
            },
        ),
        migrations.CreateModel(
            name='BorrowType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_category', models.CharField(default='', max_length=100, verbose_name='外借种类')),
                ('b_subject', models.CharField(blank=True, default='', max_length=100, verbose_name='外借小类')),
                ('flexible', models.TextField(blank=True, default='', null=True, verbose_name='保留列')),
            ],
            options={
                'verbose_name': '外借工时分类',
                'verbose_name_plural': '外借工时分类',
            },
        ),
        migrations.CreateModel(
            name='GroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='组')),
            ],
            options={
                'verbose_name': '组权限',
                'verbose_name_plural': '组权限',
            },
        ),
        migrations.CreateModel(
            name='ManHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_fix_date', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='最后修改时间')),
                ('create_date', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='创建时间')),
                ('contract', models.CharField(default='', max_length=30, verbose_name='合同号')),
                ('sfg', models.CharField(default='', max_length=15, verbose_name='SFG')),
                ('product_type', models.CharField(default='', max_length=50, verbose_name='机型')),
                ('prob', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='测头')),
                ('qty', models.FloatField(default='', max_length=4, verbose_name='数量')),
                ('standard', models.FloatField(default=0, max_length=4, verbose_name='标准价值工时')),
                ('real_time', models.FloatField(default=0, max_length=4, verbose_name='实际工时')),
                ('confirmed', models.FloatField(blank=True, default=0, max_length=4, verbose_name='确认价值工时')),
                ('quote', models.FloatField(default=0, max_length=4, verbose_name='报价')),
                ('cost_rate', models.FloatField(default=0, max_length=4, verbose_name='费率')),
                ('date', models.DateField()),
                ('original_group', models.CharField(default='', max_length=20, verbose_name='原班组')),
                ('work_group', models.CharField(default='', max_length=20, verbose_name='工作组')),
                ('last_fix_user', models.CharField(default='', max_length=5, verbose_name='最后修改人')),
                ('last_fix_status', models.CharField(default='', max_length=1000, verbose_name='最后修改状态')),
                ('is_active', models.BooleanField(default=False)),
                ('flexible', models.TextField(blank=True, default='', null=True, verbose_name='浮动列')),
                ('op', models.ForeignKey(db_column='op_id', on_delete=django.db.models.deletion.CASCADE, to='report.Op', verbose_name='工步')),
                ('username', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户名')),
            ],
            options={
                'verbose_name': '制造工时统计',
                'verbose_name_plural': '制造工时统计',
            },
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=300, verbose_name='一级菜单')),
                ('subtitle', models.CharField(default='', max_length=300, verbose_name='二级菜单')),
                ('subtitle2', models.CharField(blank=True, default='', max_length=300, verbose_name='三级菜单')),
                ('url', models.CharField(default='', max_length=200, verbose_name='URL')),
                ('flexible', models.TextField(blank=True, default='', null=True, verbose_name='浮动列')),
            ],
            options={
                'verbose_name': '所有权限',
                'verbose_name_plural': '所有权限',
            },
        ),
        migrations.CreateModel(
            name='UserInfomation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_no', models.CharField(default='', max_length=10, verbose_name='工号')),
                ('duty', models.CharField(default='', max_length=10, verbose_name='职位')),
                ('email', models.CharField(blank=True, default='', max_length=50, verbose_name='邮箱')),
                ('original_group', models.CharField(default='', max_length=30, verbose_name='原班组')),
                ('mobile', models.IntegerField(blank=True, verbose_name='电话')),
                ('cost_rate', models.FloatField(default=0, max_length=4, verbose_name='费率')),
                ('quote', models.FloatField(default=0, max_length=4, verbose_name='报价')),
                ('flexible', models.TextField(blank=True, default='', null=True, verbose_name='浮动列')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否生效')),
                ('permissions', models.ManyToManyField(blank=True, to='jzgs.Permissions', verbose_name='个人权限')),
                ('user_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True, verbose_name='用户名')),
                ('work_group', models.ForeignKey(db_column='group_name', default='', on_delete=django.db.models.deletion.CASCADE, to='report.WorkGroups', verbose_name='工作组')),
            ],
            options={
                'verbose_name': '用户信息表',
                'verbose_name_plural': '用户信息表',
            },
        ),
        migrations.AddField(
            model_name='grouppermissions',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='jzgs.Permissions', verbose_name='组权限'),
        ),
    ]
