# Generated by Django 2.1.1 on 2019-08-23 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jzgs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assistance',
            options={'verbose_name': '非制造工时统计', 'verbose_name_plural': '非制造工时统计'},
        ),
        migrations.AlterModelOptions(
            name='assistype',
            options={'verbose_name': '非制造工时种类', 'verbose_name_plural': '非制造工时种类'},
        ),
        migrations.AlterModelOptions(
            name='userinfomation',
            options={'verbose_name': '用户信息表', 'verbose_name_plural': '用户信息表'},
        ),
        migrations.AddField(
            model_name='userinfomation',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='是否生效'),
        ),
        migrations.AlterField(
            model_name='assistance',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 8, 23, 9, 46, 0, 619324)),
        ),
    ]
