# Generated by Django 2.1.1 on 2019-11-26 18:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('jzgs', '0001_initial'),
    ]

    operations = [

       
         
    ]
