# Generated by Django 2.1.1 on 2019-11-28 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jzgs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfomation',
            name='hiredate',
            field=models.DateField(default=datetime.date(2019, 11, 28), verbose_name='入职时间'),
        ),
    ]
