# Generated by Django 2.1.1 on 2020-01-07 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jzgs', '0002_auto_20191128_1821'),
    ]

    operations = [
      
    ]
