# Generated by Django 2.1.1 on 2019-08-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jzgs', '0002_auto_20190823_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_category', models.CharField(default='', max_length=100, verbose_name='外借种类')),
                ('b_subject', models.CharField(blank=True, default='', max_length=100, verbose_name='外借小类')),
                ('flexible', models.TextField(blank=True, default='', null=True, verbose_name='保留列')),
            ],
            options={
                'verbose_name': '外借工时分类',
                'verbose_name_plural': '外借工时分类',
            },
        ),
        migrations.AlterField(
            model_name='assistance',
            name='confirmed',
            field=models.FloatField(default=0, max_length=4, verbose_name='确认价值工时'),
        ),
        migrations.AlterField(
            model_name='assistance',
            name='cost_rate',
            field=models.FloatField(default=0, max_length=4, verbose_name='费率'),
        ),
        migrations.AlterField(
            model_name='assistance',
            name='create_date',
            field=models.DateTimeField(auto_created=True, auto_now=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='assistance',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='assistance',
            name='expense',
            field=models.FloatField(blank=True, default=0, max_length=10, verbose_name='期间费用'),
        ),
        migrations.AlterField(
            model_name='assistance',
            name='last_fix_date',
            field=models.DateTimeField(auto_created=True, auto_now=True, verbose_name='最后修改时间'),
        ),
        migrations.AlterField(
            model_name='assistance',
            name='quote',
            field=models.FloatField(default=0, max_length=4, verbose_name='报价'),
        ),
        migrations.AlterField(
            model_name='assistance',
            name='real_time',
            field=models.FloatField(default=0, max_length=4, verbose_name='实际工时'),
        ),
        migrations.AlterField(
            model_name='assistance',
            name='standard',
            field=models.FloatField(default=0, max_length=4, verbose_name='标准价值工时'),
        ),
        migrations.AlterField(
            model_name='assistype',
            name='b_category',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='外借科目大类'),
        ),
        migrations.AlterField(
            model_name='assistype',
            name='b_subject',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='外借科目小类'),
        ),
        migrations.AlterField(
            model_name='assistype',
            name='create_date',
            field=models.DateTimeField(auto_created=True, auto_now=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='assistype',
            name='flexible',
            field=models.TextField(blank=True, default='', null=True, verbose_name='保留列'),
        ),
        migrations.AlterField(
            model_name='assistype',
            name='last_fix_date',
            field=models.DateTimeField(auto_created=True, auto_now=True, verbose_name='最后修改时间'),
        ),
        migrations.AlterField(
            model_name='manhours',
            name='confirmed',
            field=models.FloatField(blank=True, default=0, max_length=4, verbose_name='确认价值工时'),
        ),
        migrations.AlterField(
            model_name='manhours',
            name='cost_rate',
            field=models.FloatField(default=0, max_length=4, verbose_name='费率'),
        ),
        migrations.AlterField(
            model_name='manhours',
            name='create_date',
            field=models.DateTimeField(auto_created=True, auto_now=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='manhours',
            name='last_fix_date',
            field=models.DateTimeField(auto_created=True, auto_now=True, verbose_name='最后修改时间'),
        ),
        migrations.AlterField(
            model_name='manhours',
            name='quote',
            field=models.FloatField(default=0, max_length=4, verbose_name='报价'),
        ),
        migrations.AlterField(
            model_name='manhours',
            name='real_time',
            field=models.FloatField(default=0, max_length=4, verbose_name='实际工时'),
        ),
        migrations.AlterField(
            model_name='manhours',
            name='standard',
            field=models.FloatField(default=0, max_length=4, verbose_name='标准价值工时'),
        ),
    ]
