# Generated by Django 2.1.1 on 2019-09-24 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jzgs', '0003_auto_20190830_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='组')),
            ],
            options={
                'verbose_name': '组权限',
                'verbose_name_plural': '组权限',
            },
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=300, verbose_name='一级菜单')),
                ('subtitle', models.CharField(default='', max_length=300, verbose_name='二级菜单')),
                ('subtitle2', models.CharField(default='', max_length=300, verbose_name='三级菜单')),
                ('url', models.CharField(default='', max_length=200, verbose_name='URL')),
                ('flexible', models.TextField(blank=True, default='', null=True, verbose_name='浮动列')),
            ],
            options={
                'verbose_name': '所有权限',
                'verbose_name_plural': '所有权限',
            },
        ),
        migrations.CreateModel(
            name='UserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissions', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='jzgs.Permissions', verbose_name='权限')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户权限',
                'verbose_name_plural': '用户权限',
            },
        ),
        migrations.AlterField(
            model_name='assistance',
            name='attach',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='附件'),
        ),
        migrations.AlterField(
            model_name='assistance',
            name='last_fix_status',
            field=models.CharField(default='', max_length=1000, verbose_name='最后修改状态'),
        ),
        migrations.AlterField(
            model_name='assistype',
            name='a_category',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='大类'),
        ),
        migrations.AlterField(
            model_name='manhours',
            name='last_fix_status',
            field=models.CharField(default='', max_length=1000, verbose_name='最后修改状态'),
        ),
        migrations.AddField(
            model_name='grouppermissions',
            name='permissions',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='jzgs.Permissions', verbose_name='权限'),
        ),
    ]
