# Generated by Django 2.1.1 on 2019-09-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jzgs', '0004_auto_20190924_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpermissions',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='userpermissions',
            name='user',
        ),
        migrations.AddField(
            model_name='userinfomation',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='jzgs.Permissions', verbose_name='个人权限'),
        ),
        migrations.RemoveField(
            model_name='grouppermissions',
            name='permissions',
        ),
        migrations.AddField(
            model_name='grouppermissions',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='jzgs.Permissions', verbose_name='组权限'),
        ),
        migrations.DeleteModel(
            name='UserPermissions',
        ),
    ]
