# Generated by Django 2.1.1 on 2019-10-23 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jzgs', '0005_auto_20190924_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistance',
            name='old_perform',
            field=models.IntegerField(default=0, verbose_name='业绩'),
        ),
        migrations.AddField(
            model_name='manhours',
            name='old_perform',
            field=models.IntegerField(default=0, verbose_name='业绩'),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='subtitle2',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='三级菜单'),
        ),
        migrations.AlterField(
            model_name='userinfomation',
            name='user_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True, verbose_name='用户名'),
        ),
    ]
